### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by AmmarFT** [Financial-Times/ft-annotations-chrome-extension#1]
Description:
Steps To Reproduce:
1. Buy a computer
2. Install Windows 10
3. Install Chrome
4. Open Chrome
4. Install FT Annotations chrome extension.
5. Browse to an article on FT.com (Next), after signing in.
6. Click on the little flower icon in the top right of Chrome which starts the FT Annotations Chrome extension.
7. Click on "set your API key"

EXPECTED
An input field should be displayed that allows you to input and submit a  valid API key. 

ACTUAL
No visible change takes place, no input field appears.

Analysis:

This issue is likely security related given it's a Chrome extension and a link within it. This suggests not enough testing of this extension took place before it was released. 

There is a workaround where you can input the API key via the Chrome browser settings for the extension.

**Comment by davidlintonattheft** [comment]
Fixed.
You can now always get to the options page from within the popup too.
